#Tomcat Server
spring:
  datasource:
   # url: jdbc:mysql://localhost:3306/my_library
   # username: root
   # password: Library01
    url: ${JAWSDB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
 # jpa:
   # hibernate.ddl-auto: update