#Tomcat Server
spring:
  datasource:
   # url: jdbc:mysql://localhost:3306/my_library
   # username: root
   # password: Library01
    url: jdbc:mysql://vnbygd0bdmjn9c2i:dtyvas36hsa60tcn@vhw3t8e71xdz9k14.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/bs39ivfdhxufnltr
    username: vnbygd0bdmjn9c2i
    password: dtyvas36hsa60tcn
 # jpa:
   # hibernate.ddl-auto: update