#Tomcat Server
spring:
  datasource:
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:15103/railway
    username: root
    password: 61Eh-ghEbhHHCH1fecB3HFc4D53ha5-g
 # jpa:
   # hibernate.ddl-auto: update